# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yaas_controller.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import yaas_model_pb2 as yaas__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yaas_controller.proto',
  package='org.roylance.yaas',
  syntax='proto3',
  serialized_pb=_b('\n\x15yaas_controller.proto\x12\x11org.roylance.yaas\x1a\x10yaas_model.proto\"w\n\rRequestAction\x12\x31\n\x07request\x18\x01 \x01(\x0b\x32 .org.roylance.yaas.UIYaasRequest\x12\x33\n\x08response\x18\x02 \x01(\x0b\x32!.org.roylance.yaas.UIYaasResponse\"\xfb\x02\n\x0f\x41\x64minController\x12\x42\n\x18\x63hange_password_for_user\x18\x01 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x37\n\rget_all_users\x18\x02 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x37\n\ris_user_admin\x18\x03 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12;\n\x11set_user_as_admin\x18\x04 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12>\n\x14remove_user_as_admin\x18\x05 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x35\n\x0b\x64\x65lete_user\x18\x06 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\"\xd4\x02\n\x18\x41uthenticationController\x12\x30\n\x06\x65xists\x18\x01 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12/\n\x05login\x18\x02 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x36\n\x0c\x61uthenticate\x18\x03 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x32\n\x08register\x18\x04 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12\x39\n\x0f\x63hange_password\x18\x05 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12.\n\x04save\x18\x06 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\"u\n\x14UserDeviceController\x12.\n\x04save\x18\x01 \x01(\x0b\x32 .org.roylance.yaas.RequestAction\x12-\n\x03\x61ll\x18\x02 \x01(\x0b\x32 .org.roylance.yaas.RequestActionb\x06proto3')
  ,
  dependencies=[yaas__model__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_REQUESTACTION = _descriptor.Descriptor(
  name='RequestAction',
  full_name='org.roylance.yaas.RequestAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='org.roylance.yaas.RequestAction.request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='response', full_name='org.roylance.yaas.RequestAction.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=181,
)


_ADMINCONTROLLER = _descriptor.Descriptor(
  name='AdminController',
  full_name='org.roylance.yaas.AdminController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='change_password_for_user', full_name='org.roylance.yaas.AdminController.change_password_for_user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_all_users', full_name='org.roylance.yaas.AdminController.get_all_users', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_user_admin', full_name='org.roylance.yaas.AdminController.is_user_admin', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='set_user_as_admin', full_name='org.roylance.yaas.AdminController.set_user_as_admin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='remove_user_as_admin', full_name='org.roylance.yaas.AdminController.remove_user_as_admin', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='delete_user', full_name='org.roylance.yaas.AdminController.delete_user', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=563,
)


_AUTHENTICATIONCONTROLLER = _descriptor.Descriptor(
  name='AuthenticationController',
  full_name='org.roylance.yaas.AuthenticationController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='org.roylance.yaas.AuthenticationController.exists', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='login', full_name='org.roylance.yaas.AuthenticationController.login', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authenticate', full_name='org.roylance.yaas.AuthenticationController.authenticate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='register', full_name='org.roylance.yaas.AuthenticationController.register', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='change_password', full_name='org.roylance.yaas.AuthenticationController.change_password', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='save', full_name='org.roylance.yaas.AuthenticationController.save', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=906,
)


_USERDEVICECONTROLLER = _descriptor.Descriptor(
  name='UserDeviceController',
  full_name='org.roylance.yaas.UserDeviceController',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='save', full_name='org.roylance.yaas.UserDeviceController.save', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all', full_name='org.roylance.yaas.UserDeviceController.all', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=908,
  serialized_end=1025,
)

_REQUESTACTION.fields_by_name['request'].message_type = yaas__model__pb2._UIYAASREQUEST
_REQUESTACTION.fields_by_name['response'].message_type = yaas__model__pb2._UIYAASRESPONSE
_ADMINCONTROLLER.fields_by_name['change_password_for_user'].message_type = _REQUESTACTION
_ADMINCONTROLLER.fields_by_name['get_all_users'].message_type = _REQUESTACTION
_ADMINCONTROLLER.fields_by_name['is_user_admin'].message_type = _REQUESTACTION
_ADMINCONTROLLER.fields_by_name['set_user_as_admin'].message_type = _REQUESTACTION
_ADMINCONTROLLER.fields_by_name['remove_user_as_admin'].message_type = _REQUESTACTION
_ADMINCONTROLLER.fields_by_name['delete_user'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['exists'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['login'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['authenticate'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['register'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['change_password'].message_type = _REQUESTACTION
_AUTHENTICATIONCONTROLLER.fields_by_name['save'].message_type = _REQUESTACTION
_USERDEVICECONTROLLER.fields_by_name['save'].message_type = _REQUESTACTION
_USERDEVICECONTROLLER.fields_by_name['all'].message_type = _REQUESTACTION
DESCRIPTOR.message_types_by_name['RequestAction'] = _REQUESTACTION
DESCRIPTOR.message_types_by_name['AdminController'] = _ADMINCONTROLLER
DESCRIPTOR.message_types_by_name['AuthenticationController'] = _AUTHENTICATIONCONTROLLER
DESCRIPTOR.message_types_by_name['UserDeviceController'] = _USERDEVICECONTROLLER

RequestAction = _reflection.GeneratedProtocolMessageType('RequestAction', (_message.Message,), dict(
  DESCRIPTOR = _REQUESTACTION,
  __module__ = 'yaas_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaas.RequestAction)
  ))
_sym_db.RegisterMessage(RequestAction)

AdminController = _reflection.GeneratedProtocolMessageType('AdminController', (_message.Message,), dict(
  DESCRIPTOR = _ADMINCONTROLLER,
  __module__ = 'yaas_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaas.AdminController)
  ))
_sym_db.RegisterMessage(AdminController)

AuthenticationController = _reflection.GeneratedProtocolMessageType('AuthenticationController', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATIONCONTROLLER,
  __module__ = 'yaas_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaas.AuthenticationController)
  ))
_sym_db.RegisterMessage(AuthenticationController)

UserDeviceController = _reflection.GeneratedProtocolMessageType('UserDeviceController', (_message.Message,), dict(
  DESCRIPTOR = _USERDEVICECONTROLLER,
  __module__ = 'yaas_controller_pb2'
  # @@protoc_insertion_point(class_scope:org.roylance.yaas.UserDeviceController)
  ))
_sym_db.RegisterMessage(UserDeviceController)


# @@protoc_insertion_point(module_scope)
