/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_roylance_yaas_services_AuthenticationJNIBridge */

#ifndef _Included_org_roylance_yaas_services_AuthenticationJNIBridge
#define _Included_org_roylance_yaas_services_AuthenticationJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    existsJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_existsJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    loginJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_loginJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    authenticateJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_authenticateJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    registerJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_registerJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    change_passwordJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_change_1passwordJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AuthenticationJNIBridge
 * Method:    saveJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AuthenticationJNIBridge_saveJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
