/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_roylance_yaas_services_UserDeviceJNIBridge */

#ifndef _Included_org_roylance_yaas_services_UserDeviceJNIBridge
#define _Included_org_roylance_yaas_services_UserDeviceJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_roylance_yaas_services_UserDeviceJNIBridge
 * Method:    saveJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_UserDeviceJNIBridge_saveJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_UserDeviceJNIBridge
 * Method:    allJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_UserDeviceJNIBridge_allJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
