/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_roylance_yaas_services_AdminJNIBridge */

#ifndef _Included_org_roylance_yaas_services_AdminJNIBridge
#define _Included_org_roylance_yaas_services_AdminJNIBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    change_password_for_userJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_change_1password_1for_1userJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    get_all_usersJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_get_1all_1usersJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    is_user_adminJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_is_1user_1adminJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    set_user_as_adminJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_set_1user_1as_1adminJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    remove_user_as_adminJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_remove_1user_1as_1adminJNI
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_roylance_yaas_services_AdminJNIBridge
 * Method:    delete_userJNI
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_roylance_yaas_services_AdminJNIBridge_delete_1userJNI
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
